### ISSUE TITLE
Map module

### ISSUE THREAD

**Issue by saeedseyfi** [arashm/JDate#10]
Hi,
In `jalali-date/lib/jdate.js:7` you're requiring `map` in a `try/catch`.
Why you required two modules? Why In a `try/catch`?
And why didn't you add `map` and `map-component` in `dependencies`/`devDependencies` in `package.json`? (The bundling fails using browserify)

Best

**Comment by arashm** [comment]
Thank you. I'm planning a rewrite with current best practices.

**Comment by saeedseyfi** [comment]
Thanks for your reply Afshin.
Since I need to use it in a few hours, I can fix and create a pull request.

**Comment by arashm** [comment]
​That would be great. I would approve and release a new version as soon as
possible.​
Thank you.

**Comment by saeedseyfi** [comment]
It seems there are many errors in gulp.
If you let me, I can refactor/rewrite gulp and the module bundler (browserify).

**Comment by arashm** [comment]
Sure, but not sure if it worth the effort. The lib has dated (along with its dependencies, like gulp as you mentioned). I started a rewrite on a [different branch](https://github.com/arashm/JDate/tree/v1.0.0) a couple of months ago, but I couldn't finish it since my ideas ended-up wrong and didn't have much time since then. So, it's not in a usable state.
In any case, if you want to spend time on it, it's fine and I will merge it, but it will get rewritten later in future with the new stack, webpack and ES6...

**Comment by arashm** [comment]
Released version `1.0.0`. Hopefully this is resolved on this version.

**Comment by saeedseyfi** [comment]
Thanks :)
